services:
  carvekit_api:
    image: anodev/carvekit:latest-cuda
    ports:
      - "5000:5000"  # 5000
    environment:
      - CARVEKIT_PORT=5000
      - CARVEKIT_HOST=0.0.0.0
      - CARVEKIT_SEGMENTATION_NETWORK=tracer_b7  # can be u2net, tracer_b7, basnet, deeplabv3
      - CARVEKIT_PREPROCESSING_METHOD=none # can be none, stub
      - CARVEKIT_POSTPROCESSING_METHOD=fba # can be none, fba
      - CARVEKIT_DEVICE=cuda # can be cuda (req. cuda docker image), cpu
      - CARVEKIT_BATCH_SIZE_SEG=5 #  Number of images processed per one segmentation nn call. NOT USED IF WEB API IS USED
      - CARVEKIT_BATCH_SIZE_MATTING=1  # Number of images processed per one matting nn call. NOT USED IF WEB API IS USED
      - CARVEKIT_SEG_MASK_SIZE=640  # The size of the input image for the segmentation neural network.
      - CARVEKIT_MATTING_MASK_SIZE=2048   # The size of the input image for the matting neural network.
      - CARVEKIT_FP16=0 # Enables FP16 mode
      - CARVEKIT_TRIMAP_PROB_THRESHOLD=231  # Probability threshold at which the prob_filter and prob_as_unknown_area operations will be applied
      - CARVEKIT_TRIMAP_DILATION=30  # The size of the offset radius from the object mask in pixels when forming an unknown area
      - CARVEKIT_TRIMAP_EROSION=5  # The number of iterations of erosion that the object's mask will be subjected to before forming an unknown area
      - CARVEKIT_AUTH_ENABLE=1  # Enables authentication by tokens
      # Tokens will be generated automatically every time the container is restarted if these ENV is not set.
      #- CARVEKIT_ADMIN_TOKEN=admin
      #- CARVEKIT_ALLOWED_TOKENS=test_token1,test_token2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]